### PR TITLE
Add "name" property in service yml file (ads.yml)

### PR DESCRIPTION
**Pull request by raphaelfeng**
It's an optional property that allows to set the service name with
folder name as default value.

"ads list" command will list it as the service name.

### CODE REVIEW

**Comment by adamcath** [comment]
What problem does this solve? An alternative would be to rename the directory. Would that work? Isn't it strange that the answer to "where does serviceX live" is not "in the directory called serviceX"?

Another alternative would be for ads to add path segments in the case of a conflict (like IntelliJ does). Would that work?

Also, you will need to write an integration test.

**Comment by raphaelfeng** [comment]
It could help decouple the service name from its directory name which makes it easier to add an existing service.

For instance, if the service is under directory "server" which is too generic to be a good service name, one can just rename the service to "ninja-service" by adding the "name" property rather than renaming the folder which may require more discussions and changes.

Using the path segment could be solution to directory name conflict, but I still want a property to directly set the service name.

**Comment by adamcath** [comment]
Alright, I'll take it if you add an integration test.

**Comment by adamcath** [comment]
Timing this out.

**Pull request closed without merging**
